import React, { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, useWindowDimensions, View } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { SafeAreaProvider, useSafeAreaInsets } from 'react-native-safe-area-context';

const C = { page: '#F2F4F8', white: '#FFFFFF', ink: '#1E293B', muted: '#64748B', border: '#E2E8F0', blue: '#2F70B5', total: '#74A1CD', unattempted: '#5D8CB7', incomplete: '#4877A1', completed: '#2F5C86' };
type Screen = 'home' | 'premises' | 'appointments' | 'tasks' | 'checkin' | 'checkout' | 'execution' | 'site' | 'unavailable' | 'reason' | 'submitted';
type Go = (screen: Screen) => void;
// Demo-only fixture: this pass changes presentation, not business data or API behavior.
const order = { number: '1100514997', building: 'BLD No 14-CD', customer: 'Sumedha Sathish Patel', floor: '10', flat: '1002' };

function Header({ title, onBack, gradient = false }: { title: string; onBack?: () => void; gradient?: boolean }) {
  const { top } = useSafeAreaInsets();
  return <View style={[s.header, gradient && s.gradient, { paddingTop: Math.max(top, 12) }]}><View style={s.headerRow}>{onBack ? <Pressable onPress={onBack} style={[s.back, gradient && s.backGradient]}><Text style={s.backText}>‹</Text></Pressable> : <View style={s.headerSpacer} />}<Text style={s.headerTitle}>{title}</Text><View style={s.headerSpacer} /></View></View>;
}
function Button({ label, onPress }: { label: string; onPress: () => void }) { return <Pressable onPress={onPress} style={s.button}><Text style={s.buttonText}>{label}</Text></Pressable>; }
function Card({ children, style }: { children: React.ReactNode; style?: object }) { return <View style={[s.card, style]}>{children}</View>; }
function Detail({ label, value, link = false }: { label: string; value: string; link?: boolean }) { return <View style={s.detail}><Text style={s.detailLabel}>{label}</Text><Text style={[s.detailValue, link && s.link]}>{value}</Text></View>; }
function Pill() { return <View style={s.pill}><Text style={s.pillText}>UNATTEMPTED</Text></View>; }
function Tabs({ go }: { go: Go }) { return <View style={s.tabs}><Pressable style={s.tab} onPress={() => go('home')}><Text style={s.tabIcon}>⌂</Text><Text style={s.tabLabel}>Home</Text></Pressable><View style={s.tab}><Text style={s.tabIcon}>□</Text><Text style={s.tabLabel}>Schedule</Text></View><View style={s.tab}><Text style={s.tabIcon}>⌘</Text><Text style={s.tabLabel}>Map</Text></View><View style={s.tab}><Text style={s.tabIcon}>♙</Text><Text style={s.tabLabel}>Profile</Text></View></View>; }
function Search() { return <View style={s.search}><Text style={s.searchIcon}>⌕</Text><Text style={s.searchText}>Search by ID, Customer or Area...</Text></View>; }

function Stat({ label, color, symbol, go }: { label: string; color: string; symbol: string; go: Go }) { return <Pressable onPress={() => go('premises')} style={[s.stat, { backgroundColor: color }]}><View style={s.statLeft}><View style={s.statIconBg}><Text style={s.statIcon}>{symbol}</Text></View><Text style={s.statLabel}>{label}</Text></View><Text style={s.statNumber}>0</Text></Pressable>; }
function Home({ go }: { go: Go }) {
  const { top } = useSafeAreaInsets();
  return <View style={s.screen}><View style={[s.homeHero, { paddingTop: Math.max(top, 12) }]}><View style={s.homeStatus}><Text style={s.statusTime}>05:24 pm</Text><Text style={s.statusIcons}>▂▅▇  ◠  ▭</Text></View><Text style={s.homeTitle}>Home</Text><View style={s.greetingWrap}><Text style={s.greetingTime}>05:24 pm</Text><Text style={s.greeting}>Good Evening, got supervisor! Let's get started!</Text></View></View><ScrollView contentContainerStyle={s.homeContent} showsVerticalScrollIndicator={false}><Stat label="Total" color={C.total} symbol="☷" go={go} /><Stat label="Unattempted" color={C.unattempted} symbol="−" go={go} /><Stat label="Incomplete" color={C.incomplete} symbol="×" go={go} /><Stat label="Completed" color={C.completed} symbol="✓" go={go} /></ScrollView></View>;
}
function Premises({ go }: { go: Go }) { return <View style={s.screen}><Header title="Premises" onBack={() => go('home')} gradient /><ScrollView contentContainerStyle={s.listContent}><Search /><Text style={s.sectionLabel}>Buildings (1)</Text><Pressable style={s.buildingCard} onPress={() => go('appointments')}><View style={s.buildingDetails}><Detail label="Building Name" value={order.building} /><Detail label="District" value="CHEMBUR" /><Detail label="Activity Year" value="2026" /><Detail label="Count" value="10" link /></View><View style={s.chevronCircle}><Text style={s.chevron}>›</Text></View></Pressable></ScrollView><Tabs go={go} /></View>; }
function Appointments({ go }: { go: Go }) { return <View style={s.screen}><Header title="Work Orders" onBack={() => go('premises')} gradient /><ScrollView contentContainerStyle={s.listContent}><Search /><Text style={s.sectionLabel}>Total (1)</Text><Pressable onPress={() => go('tasks')} style={s.appointment}><View style={s.topRow}><Text style={s.orderNumber}>{order.number}</Text><Pill /></View><View style={s.line} /><Detail label="Building Name" value={order.building} /><Detail label="Customer Name" value={order.customer} /><Detail label="Floor" value={order.floor} /><Detail label="Flat" value={order.flat} /></Pressable></ScrollView><Tabs go={go} /></View>; }
function Task({ n, title, onPress }: { n: string; title: string; onPress: () => void }) { return <Pressable onPress={onPress} style={s.task}><View style={s.taskCircle}><Text style={s.taskN}>{n}</Text></View><Text style={s.taskTitle}>{title}</Text><Text style={s.pending}>Pending</Text></Pressable>; }
function Tasks({ go }: { go: Go }) { return <View style={s.screen}><Header title="Work Order Tasks" onBack={() => go('appointments')} gradient /><ScrollView contentContainerStyle={s.tasksContent}><Card style={s.workCard}><View style={s.topRow}><Text style={s.orderNumber}>{order.number}</Text><Pill /></View><View style={s.detailBlock}><Detail label="Building Name" value={order.building} /><Detail label="Customer Name" value={order.customer} /><Detail label="Floor" value={order.floor} /><Detail label="Flat" value={order.flat} /></View></Card><Card style={s.taskCard}><Text style={s.taskHeading}>Tasks List</Text><Task n="1" title="Check-In" onPress={() => go('checkin')} /><Task n="2" title="Execution Details" onPress={() => go('execution')} /></Card></ScrollView></View>; }

function Choice({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={s.choice}><View style={[s.radio, selected && s.radioOn]}>{selected && <View style={s.dot} />}</View><Text style={s.choiceText}>{label}</Text></Pressable>; }
function Field({ label, placeholder, multiline = false }: { label: string; placeholder: string; multiline?: boolean }) { return <View style={s.field}><Text style={s.fieldLabel}>* <Text style={s.fieldPlain}>{label}</Text></Text><TextInput placeholder={placeholder} placeholderTextColor="#94A3B8" multiline={multiline} style={[s.input, multiline && s.textArea]} /></View>; }
function Form({ title, previous, go, onNext, nextLabel = 'Continue', children }: { title: string; previous: Screen; go: Go; onNext: () => void; nextLabel?: string; children: React.ReactNode }) { return <View style={s.screen}><Header title={title} onBack={() => go(previous)} gradient /><ScrollView contentContainerStyle={s.formContent}>{children}</ScrollView><View style={s.cta}><Button label={nextLabel} onPress={onNext} /></View></View>; }
function CheckIn({ go }: { go: Go }) { const [yes, setYes] = useState(true); return <Form title="Check-In" previous="tasks" go={go} onNext={() => go(yes ? 'checkout' : 'unavailable')}><Card><Text style={s.cardTitle}>Is Customer Available?</Text><Choice label="Yes" selected={yes} onPress={() => setYes(true)} /><Choice label="No" selected={!yes} onPress={() => setYes(false)} /></Card></Form>; }
function Checkout({ go }: { go: Go }) { const [yes, setYes] = useState(true); return <Form title="Check-Out" previous="checkin" go={go} onNext={() => go(yes ? 'execution' : 'site')}><Card><Text style={s.cardTitle}>Is Meter Available?</Text><Choice label="Yes" selected={yes} onPress={() => setYes(true)} /><Choice label="No" selected={!yes} onPress={() => setYes(false)} /><Field label="Remarks" placeholder="Enter remarks" multiline /></Card></Form>; }
function Execution({ go }: { go: Go }) { return <Form title="Execution Details" previous="checkout" go={go} onNext={() => go('site')}><Card><Text style={s.cardTitle}>Rubber Hose details</Text><Field label="Meter Number" placeholder="Enter meter number" /><Field label="Meter Reading" placeholder="Enter meter reading" /><Field label="Old Rubber Hose Expiry" placeholder="Select date" /></Card></Form>; }
function Site({ go }: { go: Go }) { return <Form title="Site Details" previous="execution" go={go} onNext={() => go('submitted')} nextLabel="Submit"><Card><Text style={s.cardTitle}>Rubber Hose details</Text><Field label="Number Of leakage Observed" placeholder="Select" /><Field label="Leakage Location 1" placeholder="Select" /><Field label="Leakage Location 2" placeholder="Select" /></Card></Form>; }
function Unavailable({ go }: { go: Go }) { const [yes, setYes] = useState(false); return <Form title="Check Customer Availability" previous="checkin" go={go} onNext={() => go(yes ? 'reason' : 'site')}><Card><Text style={s.cardTitle}>Riser Activity Possible or not?</Text><Choice label="Yes" selected={yes} onPress={() => setYes(true)} /><Choice label="No" selected={!yes} onPress={() => setYes(false)} /></Card></Form>; }
function Reason({ go }: { go: Go }) { return <Form title="Reason for Cancellation" previous="unavailable" go={go} onNext={() => go('submitted')} nextLabel="Submit"><Card><Text style={s.cardTitle}>Customer Not Allowed</Text><Choice label="House Locked" selected={false} onPress={() => {}} /><Choice label="Customer Not Allowed" selected onPress={() => {}} /><Choice label="False Complaint" selected={false} onPress={() => {}} /></Card></Form>; }
function Submitted({ go }: { go: Go }) { return <View style={s.submitted}><Text style={s.success}>✓</Text><Text style={s.submittedTitle}>Work order submitted</Text><Text style={s.submittedCopy}>The work order has been recorded successfully.</Text><Button label="Back to Home" onPress={() => go('home')} /></View>; }
function Main() { const [screen, go] = useState<Screen>('home'); const page = useMemo(() => { switch (screen) { case 'home': return <Home go={go} />; case 'premises': return <Premises go={go} />; case 'appointments': return <Appointments go={go} />; case 'tasks': return <Tasks go={go} />; case 'checkin': return <CheckIn go={go} />; case 'checkout': return <Checkout go={go} />; case 'execution': return <Execution go={go} />; case 'site': return <Site go={go} />; case 'unavailable': return <Unavailable go={go} />; case 'reason': return <Reason go={go} />; default: return <Submitted go={go} />; } }, [screen]); const { width } = useWindowDimensions(); return <View style={[s.frame, width >= 768 && s.tablet]}>{page}</View>; }
export default function App() { return <SafeAreaProvider><StatusBar style="light" /><Main /></SafeAreaProvider>; }

const s = StyleSheet.create({
  frame: { flex: 1, backgroundColor: C.page, width: '100%', alignSelf: 'center' }, tablet: { maxWidth: 720, borderLeftWidth: 1, borderRightWidth: 1, borderColor: C.border }, screen: { flex: 1, backgroundColor: C.page },
  header: { backgroundColor: C.blue, paddingBottom: 8 }, gradient: { backgroundColor: '#218D97' }, headerRow: { height: 56, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center' }, headerTitle: { flex: 1, color: C.white, fontSize: 18, fontWeight: '700' }, headerSpacer: { width: 36 }, back: { width: 36, height: 36, marginRight: 12, alignItems: 'center', justifyContent: 'center' }, backGradient: { borderRadius: 18, backgroundColor: 'rgba(255,255,255,.16)' }, backText: { color: C.white, fontSize: 36, lineHeight: 36, marginTop: -5 },
  homeHero: { backgroundColor: C.blue, paddingBottom: 24 }, homeStatus: { height: 32, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, statusTime: { color: C.white, fontSize: 14, fontWeight: '600' }, statusIcons: { color: C.white, fontSize: 16 }, homeTitle: { color: C.white, fontSize: 18, fontWeight: '700', marginHorizontal: 16, marginTop: 8 }, greetingWrap: { alignItems: 'center', paddingHorizontal: 20, marginTop: 12, gap: 8 }, greetingTime: { color: C.white, fontSize: 28, fontWeight: '700' }, greeting: { color: C.white, fontSize: 14, textAlign: 'center' }, homeContent: { padding: 16, gap: 12, paddingBottom: 32 }, stat: { height: 72, borderRadius: 12, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, statLeft: { flexDirection: 'row', gap: 12, alignItems: 'center' }, statIconBg: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,.25)' }, statIcon: { color: C.white, fontSize: 24, fontWeight: '700' }, statLabel: { color: C.white, fontSize: 16, fontWeight: '600' }, statNumber: { color: C.white, fontSize: 28, fontWeight: '700' },
  listContent: { padding: 16, gap: 16, paddingBottom: 24 }, search: { height: 42, borderRadius: 21, borderWidth: 1, borderColor: C.border, backgroundColor: C.white, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', gap: 12 }, searchIcon: { color: C.muted, fontSize: 29, lineHeight: 30, transform: [{ rotate: '-20deg' }] }, searchText: { color: C.muted, fontSize: 16, flexShrink: 1 }, sectionLabel: { marginLeft: 8, color: C.ink, fontSize: 16, fontWeight: '700' }, buildingCard: { minHeight: 118, borderRadius: 16, borderWidth: 1, borderColor: C.border, backgroundColor: C.white, padding: 16, flexDirection: 'row', alignItems: 'center' }, buildingDetails: { flex: 1, gap: 6 }, detail: { minHeight: 17, flexDirection: 'row', alignItems: 'center' }, detailLabel: { flexBasis: 118, color: C.muted, fontSize: 13 }, detailValue: { flex: 1, color: C.ink, fontSize: 13, fontWeight: '600' }, link: { color: '#4777C1', textDecorationLine: 'underline' }, chevronCircle: { width: 32, height: 32, borderRadius: 16, backgroundColor: C.white, alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOpacity: .16, shadowRadius: 7, shadowOffset: { width: 0, height: 2 }, elevation: 3 }, chevron: { color: C.muted, fontSize: 32, lineHeight: 32, marginTop: -4 },
  tabs: { height: 64, backgroundColor: C.white, borderTopWidth: 1, borderColor: C.border, flexDirection: 'row', justifyContent: 'space-around', paddingTop: 7 }, tab: { alignItems: 'center', minWidth: 60 }, tabIcon: { color: C.muted, fontSize: 25, height: 31 }, tabLabel: { color: C.muted, fontSize: 12, fontWeight: '600' },
  appointment: { backgroundColor: C.white, borderRadius: 12, borderWidth: 1, borderColor: C.border, padding: 16, gap: 10 }, topRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, orderNumber: { color: C.ink, fontSize: 16, fontWeight: '700' }, pill: { backgroundColor: '#E8F1FD', borderRadius: 12, paddingHorizontal: 10, paddingVertical: 4 }, pillText: { color: '#3569A9', fontSize: 10, fontWeight: '700' }, line: { height: 1, backgroundColor: C.border },
  tasksContent: { padding: 16, gap: 18, paddingBottom: 30 }, card: { padding: 16, borderRadius: 16, borderWidth: 1, borderColor: C.border, backgroundColor: C.white }, workCard: { gap: 22 }, detailBlock: { gap: 9 }, taskCard: { paddingTop: 28 }, taskHeading: { color: C.ink, fontSize: 18, fontWeight: '700', marginBottom: 24 }, task: { height: 72, borderBottomWidth: 1, borderColor: C.border, flexDirection: 'row', alignItems: 'center', gap: 14 }, taskCircle: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#F0F6FC', alignItems: 'center', justifyContent: 'center' }, taskN: { color: '#0878BD', fontSize: 16, fontWeight: '700' }, taskTitle: { flex: 1, color: C.ink, fontSize: 16, fontWeight: '600' }, pending: { color: C.muted, backgroundColor: '#F1F5F9', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, fontSize: 12, fontWeight: '600' },
  formContent: { padding: 16, gap: 16, paddingBottom: 96 }, cardTitle: { color: C.ink, fontSize: 16, fontWeight: '700', marginBottom: 8 }, choice: { minHeight: 42, flexDirection: 'row', alignItems: 'center', gap: 10 }, radio: { width: 20, height: 20, borderRadius: 10, borderWidth: 2, borderColor: C.muted, alignItems: 'center', justifyContent: 'center' }, radioOn: { borderColor: C.blue }, dot: { width: 10, height: 10, borderRadius: 5, backgroundColor: C.blue }, choiceText: { color: C.ink, fontSize: 14 }, field: { gap: 7, marginTop: 10 }, fieldLabel: { color: '#EF4444', fontSize: 13, fontWeight: '700' }, fieldPlain: { color: C.ink }, input: { minHeight: 44, borderWidth: 1, borderColor: C.border, borderRadius: 10, backgroundColor: C.white, paddingHorizontal: 14, color: C.ink, fontSize: 14 }, textArea: { minHeight: 92, paddingTop: 12, textAlignVertical: 'top' }, cta: { padding: 16, backgroundColor: C.white, borderTopWidth: 1, borderColor: C.border }, button: { height: 50, borderRadius: 12, backgroundColor: C.blue, alignItems: 'center', justifyContent: 'center' }, buttonText: { color: C.white, fontSize: 16, fontWeight: '700' },
  submitted: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 32, gap: 14 }, success: { color: '#4CB748', fontSize: 52, fontWeight: '700' }, submittedTitle: { color: C.ink, fontSize: 23, fontWeight: '700' }, submittedCopy: { color: C.muted, textAlign: 'center' },
});
